# Generated by Django 6.0.4 on 2026-06-04 23:29

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('knowledge', '0002_bulkimportjob_knowledgedocument_bulk_import_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkimportjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'job de importacao em lote', 'verbose_name_plural': 'jobs de importacao em lote'},
        ),
        migrations.AlterModelOptions(
            name='knowledgecollection',
            options={'ordering': ['name'], 'verbose_name': 'colecao de conhecimento', 'verbose_name_plural': 'colecoes de conhecimento'},
        ),
        migrations.AlterModelTableComment(
            name='bulkimportjob',
            table_comment='Jobs de carga em lote de documentos a partir de um diretorio no disco. Cada job cria N KnowledgeDocuments na colecao de destino.',
        ),
        migrations.AlterModelTableComment(
            name='knowledgechunk',
            table_comment='Chunks indexados de documentos institucionais com embeddings pgvector. Consultado pelo RAGService via l2_distance para busca semantica.',
        ),
        migrations.AlterModelTableComment(
            name='knowledgecollection',
            table_comment='Colecoes de documentos institucionais. Controla acesso via grupos Django e agrupa KnowledgeDocument para fins de RAG.',
        ),
        migrations.AlterModelTableComment(
            name='knowledgedocument',
            table_comment='Documentos institucionais indexados no pipeline RAG. Cada documento origina N KnowledgeChunk com embedding pgvector. Pode ser originado por upload HTTP ou por carga em lote via BulkImportJob.',
        ),
        migrations.RemoveConstraint(
            model_name='knowledgechunk',
            name='knowledge_knowledgechunk_document_chunk_index_uniq',
        ),
        migrations.AlterField(
            model_name='bulkimportjob',
            name='celery_task_id',
            field=models.CharField(blank=True, db_comment='Task ID retornado pelo Celery ao disparar run_bulk_import.', default='', help_text='ID da task Celery que executa este job.', max_length=255, verbose_name='ID da task Celery'),
        ),
        migrations.AlterField(
            model_name='bulkimportjob',
            name='collection',
            field=models.ForeignKey(db_comment='Colecao de destino dos documentos importados.', on_delete=django.db.models.deletion.CASCADE, related_name='bulk_import_jobs', to='knowledge.knowledgecollection', verbose_name='colecao'),
        ),
        migrations.AlterField(
            model_name='bulkimportjob',
            name='failed_files',
            field=models.IntegerField(db_comment='Arquivos que geraram erro ao tentar criar o KnowledgeDocument.', default=0, help_text='Arquivos que falharam durante a criacao do documento.', verbose_name='arquivos com falha'),
        ),
        migrations.AlterField(
            model_name='bulkimportjob',
            name='file_extensions',
            field=models.JSONField(blank=True, db_comment='Filtro de extensoes; lista vazia = todas as extensoes suportadas.', default=list, help_text='Lista de extensoes sem ponto (ex: ["pdf", "docx"]). Vazio = aceita todas: pdf, docx, txt, md.', verbose_name='extensoes aceitas'),
        ),
        migrations.AlterField(
            model_name='bulkimportjob',
            name='id',
            field=models.UUIDField(db_comment='UUID do job de importacao em lote.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bulkimportjob',
            name='indexed_files',
            field=models.IntegerField(db_comment='Documentos criados com sucesso e indexacao enfileirada.', default=0, help_text='Arquivos cujos documentos foram criados e enfileirados para indexacao.', verbose_name='arquivos enfileirados'),
        ),
        migrations.AlterField(
            model_name='bulkimportjob',
            name='recursive',
            field=models.BooleanField(db_comment='Indica se a varredura deve ser recursiva.', default=True, help_text='Se marcado, percorre subdiretorios recursivamente.', verbose_name='recursivo'),
        ),
        migrations.AlterField(
            model_name='bulkimportjob',
            name='source_directory',
            field=models.CharField(db_comment='Caminho absoluto do diretorio de origem dos documentos.', help_text='Caminho absoluto do diretorio no servidor onde estao os documentos. Deve ser acessivel pelo worker Celery.', max_length=1000, verbose_name='diretorio de origem'),
        ),
        migrations.AlterField(
            model_name='bulkimportjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('completed', 'Concluido'), ('completed_with_errors', 'Concluido com erros'), ('failed', 'Falha')], db_comment='Estado do job: pending -> running -> completed/completed_with_errors/failed.', db_index=True, default='pending', help_text='Estado atual do job de importacao.', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='bulkimportjob',
            name='total_files',
            field=models.IntegerField(db_comment='Total de arquivos elegiveis para importacao.', default=0, help_text='Total de arquivos encontrados no diretorio.', verbose_name='total de arquivos'),
        ),
        migrations.AlterField(
            model_name='bulkimportjob',
            name='triggered_by',
            field=models.ForeignKey(blank=True, db_comment='Usuario que iniciou o job de importacao em lote.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='disparado por'),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='chunk_index',
            field=models.IntegerField(db_comment='Ordem do chunk dentro do documento (0-based).', help_text='Posicao do chunk no documento original (0-based).', verbose_name='indice do chunk'),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='collection_id',
            field=models.UUIDField(db_comment='UUID desnormalizado da KnowledgeCollection para filtrar chunks por colecao sem JOIN no momento da busca vetorial.', db_index=True, help_text='UUID da colecao (desnormalizado para buscas eficientes no pgvector).', verbose_name='ID da colecao'),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='content',
            field=models.TextField(db_comment='Texto do chunk pos-mascaramento Presidio.', help_text='Texto do chunk apos extracao e mascaramento PII/LGPD.', verbose_name='conteudo'),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='document',
            field=models.ForeignKey(db_comment='Documento do qual este chunk foi extraido.', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument', verbose_name='documento'),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(db_comment='Embedding pgvector (384d, all-MiniLM-L6-v2) para busca L2.', dimensions=384, help_text='Vetor de 384 dimensoes gerado pelo modelo all-MiniLM-L6-v2.', verbose_name='embedding'),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='id',
            field=models.UUIDField(db_comment='UUID do chunk.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='knowledgecollection',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos Django que podem acessar esta colecao. Deixe em branco para acesso publico a qualquer usuario autenticado.', related_name='knowledge_collections', to='auth.group', verbose_name='grupos com acesso'),
        ),
        migrations.AlterField(
            model_name='knowledgecollection',
            name='description',
            field=models.TextField(blank=True, db_comment='Texto livre descrevendo o conteudo da colecao.', default='', help_text='Descricao do conteudo e finalidade da colecao.', verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='knowledgecollection',
            name='id',
            field=models.UUIDField(db_comment='UUID da colecao.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='knowledgecollection',
            name='is_active',
            field=models.BooleanField(db_comment='Flag de ativacao; FALSE exclui das buscas RAG.', default=True, help_text='Colecoes inativas sao ignoradas pelo pipeline RAG.', verbose_name='ativa'),
        ),
        migrations.AlterField(
            model_name='knowledgecollection',
            name='name',
            field=models.CharField(db_comment='Nome unico da colecao institucional.', help_text="Nome unico da colecao (ex: 'RH - Politicas Internas').", max_length=200, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='bulk_import_job',
            field=models.ForeignKey(blank=True, db_comment='Job de carga em lote que originou este documento (NULL para uploads manuais).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='knowledge.bulkimportjob', verbose_name='job de importacao em lote'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='chunks_count',
            field=models.IntegerField(db_comment='Total de chunks indexados no pgvector.', default=0, help_text='Quantidade de chunks gerados apos indexacao bem-sucedida.', verbose_name='numero de chunks'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='collection',
            field=models.ForeignKey(db_comment='Colecao a qual este documento pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.knowledgecollection', verbose_name='colecao'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='error_message',
            field=models.TextField(blank=True, db_comment='Mensagem de erro da ultima tentativa falha.', default='', help_text='Detalhes do erro ocorrido durante a indexacao.', verbose_name='mensagem de erro'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='file_path',
            field=models.CharField(db_comment='Caminho absoluto do arquivo no servidor.', help_text='Caminho absoluto do arquivo no filesystem (acessivel pelo worker Celery).', max_length=1000, verbose_name='caminho do arquivo'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT'), ('md', 'Markdown')], db_comment='Formato do arquivo (pdf, docx, txt, md).', help_text='Formato do arquivo para extracao de texto.', max_length=10, verbose_name='tipo de arquivo'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='id',
            field=models.UUIDField(db_comment='UUID do documento.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='ingested_by',
            field=models.ForeignKey(blank=True, db_comment='Usuario que realizou o upload/ingestion do documento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingested_documents', to=settings.AUTH_USER_MODEL, verbose_name='ingerido por'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('indexing', 'Indexando'), ('ready', 'Pronto'), ('error', 'Erro')], db_comment='Estado de processamento: pending -> indexing -> ready/error.', db_index=True, default='pending', help_text='Estado atual do processamento do documento.', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='title',
            field=models.CharField(db_comment='Titulo descritivo do documento usado como fonte no RAG.', help_text='Titulo descritivo exibido nas respostas do RAG como fonte.', max_length=300, verbose_name='titulo'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgechunk',
            unique_together={('document', 'chunk_index')},
        ),
    ]
