# Generated by Django 6.0.4 on 2026-06-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Timestamp de criação do registro (UTC, preenchido automaticamente).', verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Timestamp da última atualização do registro (UTC, atualizado automaticamente).', verbose_name='atualizado em'),
        ),
    ]
